package org.acme;

public class GithubMockResponses {

    public static String getUserRepos() {
        return """
                [
                    {
                        "id": 876873493,
                        "node_id": "R_kgDONEQHFQ",
                        "name": "android",
                        "full_name": "user1234/android",
                        "private": false,
                        "owner": {
                            "login": "user1234",
                            "id": 88162485,
                            "node_id": "MDQ6VXNlcjg4MTYyNDg1",
                            "avatar_url": "https://avatars.githubusercontent.com/u/88162485?v=4",
                            "gravatar_id": "",
                            "url": "https://api.github.com/users/user1234",
                            "html_url": "https://github.com/user1234",
                            "followers_url": "https://api.github.com/users/user1234/followers",
                            "following_url": "https://api.github.com/users/user1234/following{/other_user}",
                            "gists_url": "https://api.github.com/users/user1234/gists{/gist_id}",
                            "starred_url": "https://api.github.com/users/user1234/starred{/owner}{/repo}",
                            "subscriptions_url": "https://api.github.com/users/user1234/subscriptions",
                            "organizations_url": "https://api.github.com/users/user1234/orgs",
                            "repos_url": "https://api.github.com/users/user1234/repos",
                            "events_url": "https://api.github.com/users/user1234/events{/privacy}",
                            "received_events_url": "https://api.github.com/users/user1234/received_events",
                            "type": "User",
                            "user_view_type": "public",
                            "site_admin": false
                        },
                        "html_url": "https://github.com/user1234/android",
                        "description": "Bitwarden mobile app for Android.",
                        "fork": false,
                        "url": "https://api.github.com/repos/user1234/android",
                        "forks_url": "https://api.github.com/repos/user1234/android/forks",
                        "keys_url": "https://api.github.com/repos/user1234/android/keys{/key_id}",
                        "collaborators_url": "https://api.github.com/repos/user1234/android/collaborators{/collaborator}",
                        "teams_url": "https://api.github.com/repos/user1234/android/teams",
                        "hooks_url": "https://api.github.com/repos/user1234/android/hooks",
                        "issue_events_url": "https://api.github.com/repos/user1234/android/issues/events{/number}",
                        "events_url": "https://api.github.com/repos/user1234/android/events",
                        "assignees_url": "https://api.github.com/repos/user1234/android/assignees{/user}",
                        "branches_url": "https://api.github.com/repos/user1234/android/branches{/branch}",
                        "tags_url": "https://api.github.com/repos/user1234/android/tags",
                        "blobs_url": "https://api.github.com/repos/user1234/android/git/blobs{/sha}",
                        "git_tags_url": "https://api.github.com/repos/user1234/android/git/tags{/sha}",
                        "git_refs_url": "https://api.github.com/repos/user1234/android/git/refs{/sha}",
                        "trees_url": "https://api.github.com/repos/user1234/android/git/trees{/sha}",
                        "statuses_url": "https://api.github.com/repos/user1234/android/statuses/{sha}",
                        "languages_url": "https://api.github.com/repos/user1234/android/languages",
                        "stargazers_url": "https://api.github.com/repos/user1234/android/stargazers",
                        "contributors_url": "https://api.github.com/repos/user1234/android/contributors",
                        "subscribers_url": "https://api.github.com/repos/user1234/android/subscribers",
                        "subscription_url": "https://api.github.com/repos/user1234/android/subscription",
                        "commits_url": "https://api.github.com/repos/user1234/android/commits{/sha}",
                        "git_commits_url": "https://api.github.com/repos/user1234/android/git/commits{/sha}",
                        "comments_url": "https://api.github.com/repos/user1234/android/comments{/number}",
                        "issue_comment_url": "https://api.github.com/repos/user1234/android/issues/comments{/number}",
                        "contents_url": "https://api.github.com/repos/user1234/android/contents/{+path}",
                        "compare_url": "https://api.github.com/repos/user1234/android/compare/{base}...{head}",
                        "merges_url": "https://api.github.com/repos/user1234/android/merges",
                        "archive_url": "https://api.github.com/repos/user1234/android/{archive_format}{/ref}",
                        "downloads_url": "https://api.github.com/repos/user1234/android/downloads",
                        "issues_url": "https://api.github.com/repos/user1234/android/issues{/number}",
                        "pulls_url": "https://api.github.com/repos/user1234/android/pulls{/number}",
                        "milestones_url": "https://api.github.com/repos/user1234/android/milestones{/number}",
                        "notifications_url": "https://api.github.com/repos/user1234/android/notifications{?since,all,participating}",
                        "labels_url": "https://api.github.com/repos/user1234/android/labels{/name}",
                        "releases_url": "https://api.github.com/repos/user1234/android/releases{/id}",
                        "deployments_url": "https://api.github.com/repos/user1234/android/deployments",
                        "created_at": "2024-10-22T17:37:59Z",
                        "updated_at": "2024-10-22T17:37:59Z",
                        "pushed_at": "2024-10-22T17:37:19Z",
                        "git_url": "git://github.com/user1234/android.git",
                        "ssh_url": "git@github.com:user1234/android.git",
                        "clone_url": "https://github.com/user1234/android.git",
                        "svn_url": "https://github.com/user1234/android",
                        "homepage": "https://bitwarden.com",
                        "size": 182259,
                        "stargazers_count": 0,
                        "watchers_count": 0,
                        "language": null,
                        "has_issues": false,
                        "has_projects": true,
                        "has_downloads": true,
                        "has_wiki": false,
                        "has_pages": false,
                        "has_discussions": false,
                        "forks_count": 0,
                        "mirror_url": null,
                        "archived": false,
                        "disabled": false,
                        "open_issues_count": 0,
                        "license": {
                            "key": "gpl-3.0",
                            "name": "GNU General Public License v3.0",
                            "spdx_id": "GPL-3.0",
                            "url": "https://api.github.com/licenses/gpl-3.0",
                            "node_id": "MDc6TGljZW5zZTk="
                        },
                        "allow_forking": true,
                        "is_template": false,
                        "web_commit_signoff_required": false,
                        "topics": [],
                        "visibility": "public",
                        "forks": 0,
                        "open_issues": 0,
                        "watchers": 0,
                        "default_branch": "main",
                        "permissions": {
                            "admin": true,
                            "maintain": true,
                            "push": true,
                            "triage": true,
                            "pull": true
                        }
                    },
                    {
                        "id": 876873519,
                        "node_id": "R_kgDONEQHLw",
                        "name": "clients",
                        "full_name": "user1234/clients",
                        "private": false,
                        "owner": {
                            "login": "user1234",
                            "id": 88162485,
                            "node_id": "MDQ6VXNlcjg4MTYyNDg1",
                            "avatar_url": "https://avatars.githubusercontent.com/u/88162485?v=4",
                            "gravatar_id": "",
                            "url": "https://api.github.com/users/user1234",
                            "html_url": "https://github.com/user1234",
                            "followers_url": "https://api.github.com/users/user1234/followers",
                            "following_url": "https://api.github.com/users/user1234/following{/other_user}",
                            "gists_url": "https://api.github.com/users/user1234/gists{/gist_id}",
                            "starred_url": "https://api.github.com/users/user1234/starred{/owner}{/repo}",
                            "subscriptions_url": "https://api.github.com/users/user1234/subscriptions",
                            "organizations_url": "https://api.github.com/users/user1234/orgs",
                            "repos_url": "https://api.github.com/users/user1234/repos",
                            "events_url": "https://api.github.com/users/user1234/events{/privacy}",
                            "received_events_url": "https://api.github.com/users/user1234/received_events",
                            "type": "User",
                            "user_view_type": "public",
                            "site_admin": false
                        },
                        "html_url": "https://github.com/user1234/clients",
                        "description": "Bitwarden client apps (web, browser extension, desktop, and cli).",
                        "fork": true,
                        "url": "https://api.github.com/repos/user1234/clients",
                        "forks_url": "https://api.github.com/repos/user1234/clients/forks",
                        "keys_url": "https://api.github.com/repos/user1234/clients/keys{/key_id}",
                        "collaborators_url": "https://api.github.com/repos/user1234/clients/collaborators{/collaborator}",
                        "teams_url": "https://api.github.com/repos/user1234/clients/teams",
                        "hooks_url": "https://api.github.com/repos/user1234/clients/hooks",
                        "issue_events_url": "https://api.github.com/repos/user1234/clients/issues/events{/number}",
                        "events_url": "https://api.github.com/repos/user1234/clients/events",
                        "assignees_url": "https://api.github.com/repos/user1234/clients/assignees{/user}",
                        "branches_url": "https://api.github.com/repos/user1234/clients/branches{/branch}",
                        "tags_url": "https://api.github.com/repos/user1234/clients/tags",
                        "blobs_url": "https://api.github.com/repos/user1234/clients/git/blobs{/sha}",
                        "git_tags_url": "https://api.github.com/repos/user1234/clients/git/tags{/sha}",
                        "git_refs_url": "https://api.github.com/repos/user1234/clients/git/refs{/sha}",
                        "trees_url": "https://api.github.com/repos/user1234/clients/git/trees{/sha}",
                        "statuses_url": "https://api.github.com/repos/user1234/clients/statuses/{sha}",
                        "languages_url": "https://api.github.com/repos/user1234/clients/languages",
                        "stargazers_url": "https://api.github.com/repos/user1234/clients/stargazers",
                        "contributors_url": "https://api.github.com/repos/user1234/clients/contributors",
                        "subscribers_url": "https://api.github.com/repos/user1234/clients/subscribers",
                        "subscription_url": "https://api.github.com/repos/user1234/clients/subscription",
                        "commits_url": "https://api.github.com/repos/user1234/clients/commits{/sha}",
                        "git_commits_url": "https://api.github.com/repos/user1234/clients/git/commits{/sha}",
                        "comments_url": "https://api.github.com/repos/user1234/clients/comments{/number}",
                        "issue_comment_url": "https://api.github.com/repos/user1234/clients/issues/comments{/number}",
                        "contents_url": "https://api.github.com/repos/user1234/clients/contents/{+path}",
                        "compare_url": "https://api.github.com/repos/user1234/clients/compare/{base}...{head}",
                        "merges_url": "https://api.github.com/repos/user1234/clients/merges",
                        "archive_url": "https://api.github.com/repos/user1234/clients/{archive_format}{/ref}",
                        "downloads_url": "https://api.github.com/repos/user1234/clients/downloads",
                        "issues_url": "https://api.github.com/repos/user1234/clients/issues{/number}",
                        "pulls_url": "https://api.github.com/repos/user1234/clients/pulls{/number}",
                        "milestones_url": "https://api.github.com/repos/user1234/clients/milestones{/number}",
                        "notifications_url": "https://api.github.com/repos/user1234/clients/notifications{?since,all,participating}",
                        "labels_url": "https://api.github.com/repos/user1234/clients/labels{/name}",
                        "releases_url": "https://api.github.com/repos/user1234/clients/releases{/id}",
                        "deployments_url": "https://api.github.com/repos/user1234/clients/deployments",
                        "created_at": "2024-10-22T17:38:02Z",
                        "updated_at": "2024-10-22T17:38:02Z",
                        "pushed_at": "2024-10-22T17:37:15Z",
                        "git_url": "git://github.com/user1234/clients.git",
                        "ssh_url": "git@github.com:user1234/clients.git",
                        "clone_url": "https://github.com/user1234/clients.git",
                        "svn_url": "https://github.com/user1234/clients",
                        "homepage": "https://bitwarden.com",
                        "size": 1024773,
                        "stargazers_count": 0,
                        "watchers_count": 0,
                        "language": null,
                        "has_issues": false,
                        "has_projects": true,
                        "has_downloads": true,
                        "has_wiki": false,
                        "has_pages": false,
                        "has_discussions": false,
                        "forks_count": 0,
                        "mirror_url": null,
                        "archived": false,
                        "disabled": false,
                        "open_issues_count": 0,
                        "license": {
                            "key": "other",
                            "name": "Other",
                            "spdx_id": "NOASSERTION",
                            "url": null,
                            "node_id": "MDc6TGljZW5zZTA="
                        },
                        "allow_forking": true,
                        "is_template": false,
                        "web_commit_signoff_required": false,
                        "topics": [],
                        "visibility": "public",
                        "forks": 0,
                        "open_issues": 0,
                        "watchers": 0,
                        "default_branch": "main",
                        "permissions": {
                            "admin": true,
                            "maintain": true,
                            "push": true,
                            "triage": true,
                            "pull": true
                        }
                    }
                   ]
                """;
    }

    public static String getRepoBranches() {
       return """
               [
                   {
                       "name": "master",
                       "commit": {
                           "sha": "4e6745a0b84e8fde3b0f7d8c6295d51b5e1fffb1",
                           "url": "https://api.github.com/repos/user1234/horus-recruitment-task/commits/4e6745a0b84e8fde3b0f7d8c6295d51b5e1fffb1"
                       },
                       "protected": false,
                       "protection": {
                           "enabled": false,
                           "required_status_checks": {
                               "enforcement_level": "off",
                               "contexts": [],
                               "checks": []
                           }
                       },
                       "protection_url": "https://api.github.com/repos/user1234/horus-recruitment-task/branches/master/protection"
                   },
                   {
                       "name": "test-fail-build",
                       "commit": {
                           "sha": "64cd053955b8056ed8e3a8e74532ca3f5fb8ef13",
                           "url": "https://api.github.com/repos/user1234/horus-recruitment-task/commits/64cd053955b8056ed8e3a8e74532ca3f5fb8ef13"
                       },
                       "protected": false,
                       "protection": {
                           "enabled": false,
                           "required_status_checks": {
                               "enforcement_level": "off",
                               "contexts": [],
                               "checks": []
                           }
                       },
                       "protection_url": "https://api.github.com/repos/user1234/horus-recruitment-task/branches/test-fail-build/protection"
                   }
               ]
               """;
    }
}
